### PR TITLE
Small improvement

### PR DESCRIPTION
**Pull request by Creator**
So i improved the code a little bit and looked through it. If you tell me what to do , I could help you.

PS: The code is impressive!

### CODE REVIEW

**Comment by DemHydraz** [comment]
I am going to merge this, but, please, try to be more descriptive in the pull request descriptions. Try something along the lines of:

> Improved separator discovery code in [boot.lua:35](https://github.com/Creator/Kernel/blob/48589bcb414438a68d1de5f5b7af0e644223bd5c/boot.lua#L35)

**Comment by Creator** [comment]
Ok, sure. What else can I do?

**Comment by DemHydraz** [comment]
There is nothing else on the line for now :tongue:

**Comment by Creator** [comment]
Can you add me to the Organization? You entered ccTCP. :smile:

**Comment by Creator** [comment]
Then I could help more actively.

**Comment by DemHydraz** [comment]
No.

**Pull request merged**
